version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing packages..."

  pre_build:
    commands:
      - echo "Starting Maven build..."
      - mvn clean install -DskipTests

  build:
    commands:
      - echo "Packaging build artifact..."
      # Copy jar with fixed name
      - cp target/*.jar application.jar

artifacts:
  files:
    - application.jar
    - Procfile
  discard-paths: yes
